---
title: First
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  barre:
    title: barre
    output: true
  categories:
    title: categories
    output: true
  menu-corporate:
    title: menu_corporate
    output: true
  stories:
    title: stories
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: stories
  values:
    layout: 
    stories_title: 
    stories_content: 
    safety_title1: 
    safety_title2: 
    story_logo: 
    story_solution:
    - 
    story_text1: 
    story_video: 
- scope:
    path: ''
    type: storie_title
  values:
    layout: 
    storie_title1: 
    storie_content1: 
    storie_title2: 
    storie_content2: 
    boutton_form: 
permalink: pretty
